# Generated by Django 6.0.5 on 2026-05-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=200)),
                ('match_average', models.FloatField(default=0)),
                ('count_180', models.IntegerField(default=0)),
                ('high_checkouts', models.IntegerField(default=0)),
                ('short_legs', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'match_id', 'player_name')},
            },
        ),
    ]
