# Generated by Django 6.0.5 on 2026-06-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_add_winner_img'),
        ('tournaments', '0004_add_match_statistic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchstatistic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchstatistic',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='players.player'),
        ),
        migrations.AddConstraint(
            model_name='matchstatistic',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('tournament', 'match_id', 'player'), name='unique_stat_by_player_id'),
        ),
        migrations.AddConstraint(
            model_name='matchstatistic',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', True)), fields=('tournament', 'match_id', 'player_name'), name='unique_stat_by_player_name'),
        ),
    ]
