# Generated by Django 6.0.5 on 2026-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_add_player_fk_to_matchstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstatistic',
            name='darts_per_leg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchstatistic',
            name='double_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstatistic',
            name='double_hits',
            field=models.IntegerField(default=0),
        ),
    ]
