# Generated by Django 6.0.5 on 2026-06-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_add_double_stats_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50)),
                ('legs', models.JSONField(default=list)),
                ('current_leg', models.JSONField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_legs', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'match_id')},
            },
        ),
    ]
