# Generated by Django 6.0.5 on 2026-07-12 16:01

import django.db.models.deletion
import tournaments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_add_tournament_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('active', 'Aktywny'), ('finished', 'Zakończony')], default='draft', max_length=20)),
                ('scoring_mode', models.CharField(choices=[('placement', 'Miejsce'), ('match_wins', 'Wygrane mecze')], default='placement', max_length=20)),
                ('placement_points', models.JSONField(default=tournaments.models.default_placement_points)),
                ('bonus_180_points', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_high_checkout_points', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_event', to='tournaments.tournament')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.tournamentcycle')),
            ],
            options={
                'ordering': ['order', 'planned_date', 'id'],
            },
        ),
    ]
