# Generated by Django 6.0.5 on 2026-06-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0007_training_session_double_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_private', models.BooleanField(default=False)),
                ('matches_per_pair', models.PositiveIntegerField(default=2)),
                ('points_win', models.PositiveIntegerField(default=3)),
                ('points_draw', models.PositiveIntegerField(default=1)),
                ('match_format', models.CharField(choices=[('legs', 'Legi'), ('sets', 'Sety')], default='legs', max_length=10)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('legs', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('active', 'Aktywna'), ('finished', 'Zakończona')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('pending', 'Oczekuje')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leagues.league')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_memberships', to='players.player')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveIntegerField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('finished', 'Zakończony')], default='pending', max_length=20)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='leagues.leaguemember')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='leagues.leaguemember')),
            ],
            options={
                'ordering': ['matchday', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaguemember',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('league', 'player'), name='unique_league_player'),
        ),
    ]
