# Generated by Django 6.0.5 on 2026-07-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguematch',
            name='away_count_180',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='away_high_checkouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='away_short_legs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='current_leg',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='home_count_180',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='home_high_checkouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='home_short_legs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='legs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaguematch',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('awaiting_approval', 'Do akceptacji'), ('finished', 'Zakończony')], default='pending', max_length=20),
        ),
    ]
