# Generated by Django 6.0.5 on 2026-05-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cpu',
            field=models.BooleanField(default=False),
        ),
    ]
