# Generated by Django 6.0.5 on 2026-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_add_cpu_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winner_img',
            field=models.ImageField(blank=True, null=True, upload_to='players/winner_imgs/'),
        ),
    ]
