# Generated by Django 6.0.5 on 2026-07-09 23:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_add_pending_match_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighscoreSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateField(default=datetime.date.today)),
                ('darts', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highscore_sessions', to='players.player')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
