# Generated by Django 6.0.5 on 2026-07-11 10:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_highscoresession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorPracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateField(default=datetime.date.today)),
                ('sector', models.CharField(max_length=10)),
                ('hit_rate', models.FloatField()),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_practice_sessions', to='players.player')),
            ],
            options={
                'ordering': ['-played_at', '-created_at'],
            },
        ),
    ]
